---
preset: conventionalcommits
branches: main

plugins:
    # https://github.com/semantic-release/commit-analyzer?tab=readme-ov-file#configuration
  - - "@semantic-release/commit-analyzer"
  - - "@semantic-release/release-notes-generator"
  - "@semantic-release/changelog"
  - - "@semantic-release/exec"
    - # verifyRelease - Tag has not been created (is cretaed after prepare) and version
      # has not been set at this point, so verification is not possible
      # verifyReleaseCmd: ./gradlew verifyReleaseVersion

      # prepare - set release version
      prepareCmd: ./gradlew "-PnewVersion=${nextRelease.version}" setReleaseVersion

      # publish - verify that version is release version and perform publishing tasks
      publishCmd: ./gradlew verifyReleaseVersion publishPlugins
  - - "@semantic-release/git"
    - assets:
        - CHANGELOG.md
        - version.txt
  - "@semantic-release/github"
