---
# Repository configuration for wetransform managed repositories

# Reference presets that should apply to this repository
presets: []

# List of custom required checks
required_checks:
  # check workflow is not managed, so we configure the required check manually
  - check / check / run
