name: Check

on:
  pull_request:
    branches:
      - main

jobs:
  check:
    uses: wetransform/gha-workflows/.github/workflows/gradle-library-check.yml@e369ce8f658250de66c8a7e6945bf7bb592648ab # v4.6.2
    with:
      java-version: 17
