name: Check

on:
  pull_request:
    branches:
      - main

jobs:
  check:
    uses: wetransform/gha-workflows/.github/workflows/gradle-library-check.yml@6cf8743e1cdaff405473951cc6ad4eadaf2226cc # v4.1.2
    with:
      java-version: 17
