name: Check

on:
  pull_request:
    branches:
      - main

jobs:
  check:
    uses: wetransform/gha-workflows/.github/workflows/gradle-library-check.yml@32c81994f6677a00a9d5f1fec6338ad15e641fe0 # v4.6.0
    with:
      java-version: 17
