---
#
# PLEASE NOTE: Managed workflow - do not change manually
#
name: Check commit conventions

on:
  pull_request:
    branches:
      - '*'

jobs:
  verify-commits:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

        # https://github.com/taskmedia/action-conventional-commits
      - uses: taskmedia/action-conventional-commits@866c0e6dba6aaaef9ad0939a40620b27888906c2 # v1.1.17
        with:
          types: "feat|fix|refactor|revert|ci|chore|docs|build|perf|test|style"
          skip_revert: false
